services:
  gina-reader:
    image: ghcr.io/jina-ai/reader:latest
    environment:
      - PORT=8080
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.routers.gina-reader.rule=Host(`gina-reader.pages.therry.dev`)
      - traefik.http.routers.gina-reader.entrypoints=http,https
      - traefik.http.routers.gina-reader.tls=true
      - traefik.http.routers.gina-reader.tls.certresolver=letsencrypt
      - traefik.http.services.gina-reader.loadbalancer.server.port=8081
      - traefik.docker.network=coolify

networks:
  coolify:
    external: true
